"""Gemini provider - one multimodal model does ASR and diarization together.

Unlike ElevenLabs and Sarvam, this is not a dedicated ASR service; it is a
general model that happens to understand audio. That has two consequences worth
understanding before you pick it as your default.

**Why it is attractive:** audio bills at roughly 32 tokens/second, so an hour of
meeting costs a few cents on a Flash model - meaningfully cheaper than a
per-hour ASR service. And because the model *understands* the audio rather than
just transcribing it, you can ask for per-segment language tags and speaker
turns in a single call.

**Why it may not win:** timestamps are generated by a language model rather than
produced by a forced-alignment step, so they are approximate. Our speaker
identification cuts audio at those boundaries to build voiceprints, so sloppy
timestamps degrade enrollment matching. Benchmark before trusting it - the spike
prints speaking-time-per-speaker, which is a good smell test.

**The truncation trap.** The whole transcript comes back as model *output*, so it
must fit in the output token budget. Bengali and Devanagari script run ~3x more
tokens per word than English, which makes your longest and most script-heavy
meetings the ones most likely to be cut off. We detect this by comparing the last
segment's timestamp against the true audio duration and fail loudly rather than
silently storing half a meeting.
"""

from __future__ import annotations

import logging
from pathlib import Path

from pydantic import BaseModel, Field

from app.asr.base import ASRResult, TranscriptSegment
from app.audio import duration_seconds, to_flac
from app.config import settings

log = logging.getLogger(__name__)

# Fraction of the audio that must be covered by returned segments before we
# accept the transcript as complete.
MIN_COVERAGE = 0.75

LANGUAGE_NAMES = {"en": "English", "hi": "Hindi", "bn": "Bengali"}


class _Segment(BaseModel):
    start_seconds: float = Field(description="Start time in seconds from the beginning.")
    end_seconds: float = Field(description="End time in seconds.")
    speaker: str = Field(description="Stable speaker id, e.g. SPEAKER_00, SPEAKER_01.")
    language: str = Field(description="ISO 639-1 code for this segment: en, hi or bn.")
    text: str = Field(description="Verbatim transcription in the original script.")


class _Transcript(BaseModel):
    segments: list[_Segment]
    primary_language: str = Field(description="Dominant language across the meeting.")


PROMPT = """Transcribe this meeting recording completely and verbatim.

Rules:
- Diarize. Assign every utterance a stable speaker id (SPEAKER_00, SPEAKER_01, \
...). The same person must keep the same id for the whole recording.
- Give start and end timestamps in seconds for every segment. Be precise - these \
are used to cut audio.
- Transcribe in the ORIGINAL script. Hindi in Devanagari, Bengali in Bengali \
script, English in Latin. Never transliterate and never translate.
- Speakers switch language mid-sentence. Tag each segment with the language that \
dominates it, and keep code-switched words in their own script.
- Transcribe what was actually said, including false starts and filler. Do not \
clean up, summarise, or skip inaudible stretches - mark them [inaudible].
- Cover the ENTIRE recording from start to finish. Do not stop early."""


class GeminiProvider:
    name = "gemini"

    def __init__(self, api_key: str | None = None, model: str | None = None) -> None:
        self.api_key = api_key or settings.gemini_api_key
        self.model = model or settings.gemini_model
        if not self.api_key:
            raise RuntimeError("GEMINI_API_KEY is not set")

    def transcribe(self, audio_path: Path, language_hint: str | None = None) -> ASRResult:
        from google import genai

        client = genai.Client(api_key=self.api_key)
        total_seconds = duration_seconds(audio_path)

        prompt = PROMPT
        if language_hint:
            name = LANGUAGE_NAMES.get(language_hint, language_hint)
            prompt += f"\n- The audio is primarily in {name}."
        else:
            prompt += (
                "\n- The audio may mix English, Hindi and Bengali. Detect per segment."
            )

        # Files API rather than inline data: inline caps at 20 MB total and an
        # hour of audio blows past that even compressed.
        flac = to_flac(audio_path, audio_path.with_suffix(".flac"))
        uploaded = client.files.upload(file=str(flac))

        try:
            interaction = client.interactions.create(
                model=self.model,
                input=[
                    {"type": "text", "text": prompt},
                    {
                        "type": "audio",
                        "uri": uploaded.uri,
                        "mime_type": uploaded.mime_type,
                    },
                ],
                response_format={
                    "type": "text",
                    "mime_type": "application/json",
                    "schema": _Transcript.model_json_schema(),
                },
            )
            parsed = _Transcript.model_validate_json(interaction.output_text)
        finally:
            # Uploaded meeting audio should not linger on a third party longer
            # than the request needs it.
            try:
                client.files.delete(name=uploaded.name)
            except Exception:  # noqa: BLE001
                log.warning("Could not delete uploaded file %s", uploaded.name)
            flac.unlink(missing_ok=True)

        segments = [
            TranscriptSegment(
                start=float(s.start_seconds),
                end=float(s.end_seconds),
                speaker=_normalise_speaker(s.speaker),
                text=s.text.strip(),
                language=s.language or parsed.primary_language,
            )
            for s in parsed.segments
            if s.text and s.text.strip()
        ]
        # An LLM can emit segments out of order; everything downstream assumes
        # chronological.
        segments.sort(key=lambda s: s.start)

        _assert_complete(segments, total_seconds)

        return ASRResult(
            provider=self.name,
            segments=segments,
            language=parsed.primary_language,
            words=[],
            raw={"model": self.model, "segment_count": len(segments)},
        )


def _normalise_speaker(label: str) -> str:
    """Coerce whatever the model returned into SPEAKER_NN."""
    cleaned = (label or "").strip().upper().replace(" ", "_").replace("-", "_")
    if not cleaned:
        return "SPEAKER_00"
    digits = "".join(c for c in cleaned if c.isdigit())
    return f"SPEAKER_{int(digits):02d}" if digits else cleaned


def _assert_complete(segments: list[TranscriptSegment], total_seconds: float) -> None:
    """Fail loudly if the model stopped early.

    Hitting the output token limit truncates the transcript without any error,
    which would otherwise land in the database as a complete meeting that is
    quietly missing its second half.
    """
    if not segments or total_seconds <= 0:
        return

    covered = max(s.end for s in segments)
    if covered < total_seconds * MIN_COVERAGE:
        raise RuntimeError(
            f"Gemini transcript covers only {covered:.0f}s of {total_seconds:.0f}s audio "
            f"({covered / total_seconds:.0%}). The output token limit was probably hit - "
            "likely on Bengali or Hindi, which tokenize ~3x more heavily than English. "
            "Split the recording or use a dedicated ASR provider for meetings this long."
        )
